stages:
  - stage: "cocoapods_verification"
    displayName: "CocoaPods Verification"
    dependsOn: "build"
    jobs:
      - job: "lint"
        displayName: "CocoaPods Lint Check"
        variables:
          XCODE_VERSION: "14.3.1"
        steps:
          - checkout: "none"

          - task: Bash@3
            displayName: Switch Xcode to ${XCODE_PATH}
            inputs:
              targetType: inline
              script: |
                sudo xcode-select --switch ${XCODE_PATH}

          - task: DownloadPipelineArtifact@2
            displayName: Download 'Info' Pipeline Artifact
            inputs:
              artifactName: Info
              targetPath: '$(Agent.BuildDirectory)/Info'

          - task: DownloadPipelineArtifact@2
            displayName: Download 'Release' Pipeline Artifact
            inputs:
              artifactName: Release
              targetPath: '$(Agent.BuildDirectory)/Release'

          - task: "Bash@3"
            displayName: "Patch Podspec to use local zip with PLCrashReporter"
            inputs:
              targetType: "inline"
              script: |
                sed -i '' 's|:http *=> "https://github.com/microsoft/plcrashreporter/releases/download/#{spec.version}/PLCrashReporter-Static-#{spec.version}.xcframework.zip"|:http    => "file:$(Agent.BuildDirectory)/Release/PLCrashReporter-Static-#{spec.version}.xcframework.zip"|' $(Agent.BuildDirectory)/Info/PLCrashReporter.podspec

          - task: "Bash@3"
            displayName: "CocoaPods Lint Check"
            inputs:
              targetType: "inline"
              script: |
                cd $(Agent.BuildDirectory)/Info
                pod spec lint --verbose