stages:
  - stage: "cocoapods_verification"
    displayName: "CocoaPods Verification"
    dependsOn: "build"
    jobs:
      - job: "lint"
        displayName: "CocoaPods Lint Check"
        steps:
          - checkout: "none"

          - task: DownloadPipelineArtifact@2
            displayName: Download Pipeline Artifacts for APIScan
            inputs:
              artifactName: Info
              targetPath: '$(Agent.BuildDirectory)/Info'

          - task: "Bash@3"
            displayName: "CocoaPods Lint Check"
            inputs:
              targetType: "inline"
              script: |
                cd $(Agent.BuildDirectory)/Info
                pod lib lint --verbose